"""Generate docs/baseline1-per-game-costs.md from baseline1's published run data.

Covers baseline1's two gpt-5.6-sol max runs, one table each:
  twma v1.6 max:    textual world model agent.
  ewma_sv v1.6 max: executable world model agent with verification.

Data comes from docs/baseline1_paper02/runs_additional/ (gitignored), the
per-game archives baseline1 published for its paper02 runs: each game has a
<game>_scorecard.json (server score, levels, actions) and a
<game>_cost_estimation.json (raw input/cached/output token counts and an
estimated cost at API list prices).

Usage: uv run python scripts/gen_baseline1_game_costs.py
"""

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DATA = REPO_ROOT / "docs" / "baseline1_paper02" / "runs_additional"
OUT_PATH = REPO_ROOT / "docs" / "baseline1-per-game-costs.md"

RUNS = [
    ("twma v1.6 (gpt-5.6-sol, max)", "twma_v1.6_gpt-5.6-sol_max_run1"),
    ("ewma_sv v1.6 (gpt-5.6-sol, max)", "ewma_v1.6_sv_gpt-5.6-sol_max_run1"),
]

# Same USD per MTok rates as gpt-5.6-sol; used to verify baseline1's own estimates.
INPUT_PER_MTOK, CACHED_PER_MTOK, OUTPUT_PER_MTOK = 5.0, 0.5, 30.0


def analyze(run_dir: Path, game: str):
    env = json.loads((run_dir / f"{game}_scorecard.json").read_text(encoding="utf-8"))["environments"][0]
    run = env["runs"][0]

    usage = json.loads((run_dir / f"{game}_cost_estimation.json").read_text(encoding="utf-8"))["games"][game]
    tok_in, tok_cached, tok_out = usage["input_tokens"], usage["cached_input_tokens"], usage["output_tokens"]
    cost = (
        (tok_in - tok_cached) * INPUT_PER_MTOK
        + tok_cached * CACHED_PER_MTOK
        + tok_out * OUTPUT_PER_MTOK
    ) / 1e6
    if abs(cost - usage["estimated_cost_usd"]) > 0.01:
        raise RuntimeError(f"{game}: recomputed cost {cost:.2f} != published {usage['estimated_cost_usd']:.2f}")
    return (
        env["score"],
        run["levels_completed"],
        env["level_count"],
        run["actions"],
        tok_in,
        tok_cached,
        tok_out,
        cost,
    )


def table(run_dir: Path) -> str:
    games = sorted(p.name.split("_")[0] for p in run_dir.glob("*_scorecard.json"))
    rows = []
    totals = [0, 0, 0, 0, 0.0]
    scores = []
    for game in games:
        score, done, level_count, actions, tok_in, tok_cached, tok_out, cost = analyze(run_dir, game)
        scores.append(score)
        rows.append(
            f"| {game} | {score:.2f} | {done}/{level_count} | {actions} | {tok_in / 1e6:.1f}M "
            f"| {tok_cached / 1e6:.1f}M | {tok_out / 1e6:.2f}M | {(tok_in + tok_out) / 1e6:.1f}M "
            f"| ${cost:.2f} |"
        )
        totals[0] += actions
        totals[1] += tok_in
        totals[2] += tok_cached
        totals[3] += tok_out
        totals[4] += cost
    mean_score = sum(scores) / len(scores)
    return (
        "| Game | Score | Levels | Actions | Input tokens | of which cached | Output tokens "
        "| Total tokens | Cost |\n"
        "|---|---:|---|---:|---:|---:|---:|---:|---:|\n"
        + "\n".join(rows)
        + f"\n| **Total** | **{mean_score:.2f} (mean)** | | **{totals[0]}** "
        f"| **{totals[1] / 1e6:.1f}M** | **{totals[2] / 1e6:.1f}M** | **{totals[3] / 1e6:.1f}M** "
        f"| **{(totals[1] + totals[3]) / 1e6:.1f}M** | **${totals[4]:.2f}** |\n"
    ), mean_score, totals


def main() -> None:
    sections = []
    for title, dirname in RUNS:
        tbl, mean_score, totals = table(DATA / dirname)
        sections.append(f"## {title}\n\nFrom `{dirname}`.\n\n" + tbl)
        print(f"{dirname}: mean RHAE {mean_score:.2f}, {totals[0]} actions, "
              f"{(totals[1] + totals[3]) / 1e9:.2f}B tokens, ${totals[4]:.2f}")

    doc = (
        "# baseline1 per-game costs\n\n"
        "Same shape as [per-game-costs.md](per-game-costs.md), for "
        "[baseline1](https://github.com/astroseger/arc-3-agents-baseline1)'s two gpt-5.6-sol "
        "max-effort runs, one table each: twma (textual world model agent) and ewma_sv "
        "(executable world model agent with verification, its strongest configuration). "
        "Generated by `scripts/gen_baseline1_game_costs.py` from the per-game scorecard and "
        "cost-estimation JSONs baseline1 published with its paper02 run archives.\n\n"
        "Score, levels, and actions come from each game's server scorecard; token counts are "
        "baseline1's own raw usage numbers (input includes cache reads, shown separately in "
        "the cached column). Cost is recomputed at API list prices ($5.00 input / $0.50 cached "
        "/ $30.00 output per MTok, the same rates as my runs, so the columns are "
        "arithmetically comparable) and verified against baseline1's published estimates. "
        "baseline1 ran through Codex, so this is an API-price equivalent, not what the run "
        "actually cost to whoever ran it; **tokens are the comparable measure**, cost is shown "
        "for scale.\n\n"
        + "\n".join(sections)
    )
    OUT_PATH.write_text(doc, encoding="utf-8")
    print(f"wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
