"""Generate docs/per-game-costs.md from the runs folder.

One row per game for the max-effort run: server-scored RHAE, levels, actions,
raw token counts, and API-price cost. Score, levels, and actions come from
each run's server-written scorecard.json; tokens come from transcript.jsonl
(ThinHarness per-invocation usage). Transcript records are summed across all
resume segments of the run, which is the true single-run total; metrics.json
resets its counters on some resume paths and can under-report.

Usage: uv run python scripts/gen_game_costs.py
"""

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
RUNS = REPO_ROOT / "runs"
OUT_PATH = REPO_ROOT / "docs" / "per-game-costs.md"

# gpt-5.6-sol USD per MTok; uncached input = input - cached.
INPUT_PER_MTOK, CACHED_PER_MTOK, OUTPUT_PER_MTOK = 5.0, 0.5, 30.0

# The run used for each game: the winning max-effort run.
# Update an entry when a game is re-run.
RUN_IDS = {
    "ar25": "20260719-004809",
    "bp35": "20260719-092232",
    "cd82": "20260719-065135",
    "cn04": "20260718-235556",
    "dc22": "20260718-113255",
    "ft09": "20260718-023409",
    "g50t": "20260718-180900",
    "ka59": "20260718-195135",
    "lf52": "20260718-124212",
    "lp85": "20260719-065135",
    "ls20": "20260718-154544",
    "m0r0": "20260719-051732",
    "r11l": "20260719-073300",
    "re86": "20260718-151656",
    "s5i5": "20260719-015033",
    "sb26": "20260719-062022",
    "sc25": "20260718-003331",
    "sk48": "20260718-184901",
    "sp80": "20260719-031300",
    "su15": "20260718-020421",
    "tn36": "20260718-143606",
    "tr87": "20260718-113256",
    "tu93": "20260719-052859",
    "vc33": "20260719-012937",
    "wa30": "20260719-092232",
}


def analyze(game: str, run_id: str):
    run_dir = RUNS / game / run_id
    metrics = json.loads((run_dir / "metrics.json").read_text(encoding="utf-8"))
    if metrics["stop_reason"] != "win":
        raise RuntimeError(f"{game}/{run_id}: stop_reason is {metrics['stop_reason']!r}, not a win")

    env = json.loads((run_dir / "scorecard.json").read_text(encoding="utf-8"))["environments"][0]

    tok_in = tok_cached = tok_out = 0
    for line in (run_dir / "transcript.jsonl").read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        rec = json.loads(line)
        if "invocation" not in rec:
            continue
        tok_in += rec["input_tokens"]
        tok_cached += rec["cached_tokens"]
        tok_out += rec["output_tokens"]

    cost = (
        (tok_in - tok_cached) * INPUT_PER_MTOK
        + tok_cached * CACHED_PER_MTOK
        + tok_out * OUTPUT_PER_MTOK
    ) / 1e6
    return (
        env["score"],
        env["levels_completed"],
        env["level_count"],
        env["actions"],
        tok_in,
        tok_cached,
        tok_out,
        cost,
    )


def main() -> None:
    rows = []
    totals = [0, 0, 0, 0, 0.0]
    scores = []
    for game in sorted(RUN_IDS):
        score, done, level_count, actions, tok_in, tok_cached, tok_out, cost = analyze(game, RUN_IDS[game])
        scores.append(score)
        rows.append(
            f"| {game} | {score:.2f} | {done}/{level_count} | {actions} | {tok_in / 1e6:.1f}M "
            f"| {tok_cached / 1e6:.1f}M | {tok_out / 1e6:.2f}M | {(tok_in + tok_out) / 1e6:.1f}M "
            f"| ${cost:.2f} |"
        )
        totals[0] += actions
        totals[1] += tok_in
        totals[2] += tok_cached
        totals[3] += tok_out
        totals[4] += cost
    mean_score = sum(scores) / len(scores)

    doc = (
        "# Per-game costs\n\n"
        "One row per game for the max-effort run: server-scored RHAE, levels, actions, raw "
        "token counts, and API-price cost. Generated by `scripts/gen_game_costs.py`.\n\n"
        "Sources: score, levels, and actions from each run's server-written `scorecard.json`; "
        "tokens from `transcript.jsonl` (ThinHarness per-invocation usage), summed across all "
        "resume segments of the run. Input tokens include cache reads, shown separately in the "
        "cached column. Cost at gpt-5.6-sol API list prices ($5.00 input / $0.50 cached / "
        "$30.00 output per MTok). Image-priming vision calls are not included (~cents per "
        "run).\n\n"
        "| Game | Score | Levels | Actions | Input tokens | of which cached | Output tokens "
        "| Total tokens | Cost |\n"
        "|---|---:|---|---:|---:|---:|---:|---:|---:|\n"
        + "\n".join(rows)
        + f"\n| **Total** | **{mean_score:.2f} (mean)** | | **{totals[0]}** "
        f"| **{totals[1] / 1e6:.1f}M** | **{totals[2] / 1e6:.1f}M** | **{totals[3] / 1e6:.1f}M** "
        f"| **{(totals[1] + totals[3]) / 1e6:.1f}M** | **${totals[4]:.2f}** |\n"
    )
    OUT_PATH.write_text(doc, encoding="utf-8")
    print(f"wrote {OUT_PATH}")
    print(f"mean RHAE {mean_score:.2f}, {totals[0]} actions, "
          f"{(totals[1] + totals[3]) / 1e9:.2f}B tokens, ${totals[4]:.2f}")


if __name__ == "__main__":
    main()
