"""Generate docs/baseline1-per-game-level-costs.md from baseline1's published archive.

Reads the per-game scorecard and cost-estimation JSONs from docs/baseline1_v15/
(gitignored). To set that directory up, download baseline1's v1.5 run archive
(v15.tar.gz, containing secure_baseline1_v1.5_gpt5.5_xhigh_run01/; linked from
https://github.com/astroseger/arc-3-agents-baseline1/blob/main/results/README_secure_baseline_v1.5.md)
and extract just the 50 top-level JSONs — <game>_scorecard.json and
<game>_cost_estimation.json for each of the 25 games:

    mkdir -p docs/baseline1_v15
    tar -xzf v15.tar.gz -C docs/baseline1_v15 --strip-components 1 \\
        "*/*_scorecard.json" "*/*_cost_estimation.json"

Scorecards carry per-level action counts, so actions split between cleared
levels and the uncleared level; the archive has no per-invocation usage logs,
so tokens and cost are whole-game totals from the cost-estimation files.

Usage: uv run python scripts/gen_baseline1_level_costs.py
"""

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DATA = REPO_ROOT / "docs" / "baseline1_v15"
OUT_PATH = REPO_ROOT / "docs" / "baseline1-per-game-level-costs.md"


def analyze(game: str):
    scorecard = json.loads((DATA / f"{game}_scorecard.json").read_text(encoding="utf-8"))
    costs = json.loads((DATA / f"{game}_cost_estimation.json").read_text(encoding="utf-8"))

    env = scorecard["environments"][0]
    run = env["runs"][0]
    done = run["levels_completed"]
    level_actions = run["level_actions"]
    cleared_actions = sum(level_actions[:done])
    uncleared_actions = sum(level_actions[done:]) if done < env["level_count"] else None

    usage = costs["games"][game]
    tokens = usage["input_tokens"] + usage["output_tokens"]
    return done, env["level_count"], cleared_actions, uncleared_actions, tokens, usage["estimated_cost_usd"]


def main() -> None:
    games = sorted(p.name.split("_")[0] for p in DATA.glob("*_scorecard.json"))
    rows = []
    totals = [0, 0, 0, 0.0]
    for game in games:
        done, level_count, cleared, uncleared, tokens, cost = analyze(game)
        unc_cell = "—" if uncleared is None else str(uncleared)
        rows.append(f"| {game} | {done}/{level_count} | {cleared} | {unc_cell} | {tokens / 1e6:.1f}M | ${cost:.2f} |")
        totals[0] += cleared
        totals[1] += uncleared or 0
        totals[2] += tokens
        totals[3] += cost

    doc = (
        "# baseline1 per-game level economics\n\n"
        "Same shape as [per-game-level-costs.md](per-game-level-costs.md), computed from "
        "[baseline1](https://github.com/astroseger/arc-3-agents-baseline1)'s published archive "
        "(`secure_baseline1_v1.5_gpt5.5_xhigh_run01`, gpt-5.5 at xhigh reasoning effort), one run "
        "per game. Generated by `scripts/gen_baseline1_level_costs.py` from the archive's per-game "
        "scorecard and cost-estimation JSONs; the script header documents how to download and "
        "extract them.\n\n"
        "Actions split between **cleared levels** and the **uncleared level** using the per-level "
        "action counts in each game's scorecard. The archive has no per-invocation usage logs, so "
        "**tokens and cost are whole-game totals** from baseline1's cost-estimation files. Token "
        "counts are taken directly from those files (tokens = input + output, cache reads included "
        "in input). Cost is baseline1's own `estimated_cost_usd`, computed at GPT-5.5 API list "
        "prices ($5.00 input / $0.50 cached / $30.00 output per MTok — the same rates as "
        "gpt-5.6-sol, so the columns are arithmetically comparable). baseline1 ran through Codex, "
        "so this is an API-price equivalent, not what the run actually cost to whoever ran it; "
        "**tokens are the comparable measure**, cost is shown for scale.\n\n"
        "| Game | Levels cleared | Actions (cleared) | Actions (uncleared) | Tokens (game) | Cost (game) |\n"
        "|---|---|---:|---:|---:|---:|\n"
        + "\n".join(rows)
        + f"\n| **Total** | | **{totals[0]}** | **{totals[1]}** | **{totals[2] / 1e6:.1f}M** "
        f"| **${totals[3]:.2f}** |\n"
    )
    OUT_PATH.write_text(doc, encoding="utf-8")
    print(f"wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
